# Generated by Django 5.2 on 2025-04-16 06:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classbooking',
            unique_together={('user', 'fitness_class')},
        ),
    ]
