# Generated by Django 5.2 on 2025-04-16 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('classes', '0002_alter_classbooking_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='absent', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'fitness_class', 'attendance_date')},
        ),
    ]
